spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  datasource:
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:jdbc:h2:mem:testdb}
