spring:
  jpa:
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 4632d20a47a5e8
    password: ac2a2344691f9b
    properties:
      mail:
        smtp:
          starttls:
            required: true
            enable: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  datasource:
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:jdbc:h2:mem:testdb}

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
          issuer-uri: ${AUTH0_DOMAIN:https://sbolsec.eu.auth0.com/}

auth0:
  audience: ${AUTH0_IDENTIFIER:http://localhost:8080/}
