spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
  mail:
    host: smtp.gmail.com
    port: 587
    username: pomozimiemail@gmail.com
    password: pomoziMi6!
    properties:
      mail:
        smtp:
          starttls:
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls.enable: true

  datasource:
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    url: ${DB_URL:jdbc:h2:mem:testdb}

  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithm: RS256
          issuer-uri: ${AUTH0_DOMAIN:https://sbolsec.eu.auth0.com/}

auth0:
  audience: ${AUTH0_IDENTIFIER:http://localhost:8080/}
